### ISSUE TITLE
No module named 'wget'

### ISSUE THREAD

**Issue by Lorenz11x** [aas-n/spraykatz#12]
Hi 
spraykatz# ./spraykatz.py -u H4x0r -p L0c4L4dm1n -t 192.168.1.0/24

Traceback (most recent call last):
  File "./spraykatz.py", line 11, in <module>
    from core.Resources import initSpraykatz
  File "/root/ATTACK-1-/spraykatz/core/Resources.py", line 6, in <module>
    import wget, zipfile
ModuleNotFoundError: No module named 'wget'

why??

**Comment by Lorenz11x** [comment]
#pip3 install wget
Requirement already satisfied: wget in /usr/local/lib/python3.7/dist-packages (3.2)
Not working ??! Help me pls , thanks!

**Comment by pretech86** [comment]
me also

**Comment by aas-n** [comment]
Hi,
I think you are not using the same python version for python and pip. Try to use explicit commands:
`python3.6 -m pip install -r requirements.txt`
`python3.6 spraykatz.py -u H4x0r -p L0c4L4dm1n -t 192.168.1.0/24`

Please note Spraykatz is currently not supported for python >= 3.7. Coming soon. Thanks for opening this issue.
