### ISSUE TITLE
enhacement

### ISSUE THREAD

**Issue by y0bagu1** [aas-n/spraykatz#2]
First of all, thank you for this tool!
Secondly, as an enhacement why don't you use masscan instead of nmap and add the option to add on targets file an ip on each line, it would be better for a mass aproach.
thirdly, can be multi procesing as well..for a faster aproach.
i use masscan for taking out ips and it would be much more better to add a list of ips scanned on port 135 before then scanning them with nmap.
a nice touch will be if in creds.txt will be wroted the ip too.

**Comment by aas-n** [comment]
Hi,

Thank you for your feedback.

- You can already use a file with one IP per line with the -t switch.
- With version 0.9.5, IPs are printed and written too.
- Concerning masscan & nmap, I will think about it ;).
