### ISSUE TITLE
Error occurs with target when accessing value (pypykatz)

### ISSUE THREAD

**Issue by walabus** [aas-n/spraykatz#3]
Executing spraykatz but getting error when executing the pypykatz. 

Installed on Ubuntu 18.04.

Created a test machine running Windows 2012 so fictional user accounts. 

Installed as per instructions given (https://github.com/aas-n/spraykatz)

![debug](https://user-images.githubusercontent.com/2124883/70230592-55626600-1761-11ea-802e-2aeb61d950a7.png)

**Comment by aas-n** [comment]
Hi,
Can you attach the problematic dump?

**Comment by yellow-starburst** [comment]
+1 Same error

**Comment by aas-n** [comment]
Hi,
Same answer
