### ISSUE TITLE
Error when using passwords that starts with $ character

### ISSUE THREAD

**Issue by suntop250ml** [aas-n/spraykatz#7]
I think their is an error when trying to use the tool with a password that starts with the $ character, as it is showing in the screen shots below, an error message appears at the end stating that `Error: argument -p/--password: expected one argument`

![Screenshot_1](https://user-images.githubusercontent.com/59246755/71466760-034db700-27da-11ea-9e12-3efdb8a49263.png)
![Screenshot_2](https://user-images.githubusercontent.com/59246755/71466768-0a74c500-27da-11ea-946d-a118360adc1f.png)

**Comment by aas-n** [comment]
Hi,

You can put your password between quotes and use a backslash to escape the $. 

`-p "\$password"`
